name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"
      LAMBDA_FUNCTION_NAME: "activity-pipeline-lambda"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run black
        run: |
          black --check app tests

      - name: Run pylint
        run: |
          pylint app

      - name: Run pytest with JUnit XML report
        run: |
          pytest --junitxml=test-results.xml

      - name: Archive Lambda package
        run: |
          mkdir -p lambda_package
          # Copy application code
          cp -r app lambda_package/
          cp requirements.txt lambda_package/
          # Install dependencies into package directory (Lambda-style)
          pip install -r requirements.txt -t lambda_package/
          # Create deployment zip
          cd lambda_package
          zip -r ../lambda_deploy.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name "${LAMBDA_FUNCTION_NAME}" \
            --zip-file fileb://lambda_deploy.zip
